version: '3.0'

services: 
    web:
        build: .
        command: python vitiVir_project/manage.py runserver 0.0.0.0:8000 
        volumes: 
            - .:/code 
        ports:
            - "8000:8000"
        depends_on:
            - mongo
    mongo:
        image: mongo:3.4
        restart: always
        ports:
            - 27017:27017